chore: Change constexpr to obj-c NSNumber (#3646)
Fixes
https://github.com/software-mansion/react-native-screens/issues/3549

## Description

This PR replaces constexpr declaration with equivalent NSNumber
declaration for default font sizes. We weren't able to reproduce the
compilation error, but the change doesn't have a negative impact.

## Changes

Replaced the default font size declarations.

## Test plan

Have a header (regular, large) with some non-default font family (this
triggers the font size check). Set a breakpoint in
`RNSScreenStackHeaderConfig.mm:491` and `:519` and verify the constants
are correct.

## Checklist

- [ ] Ensured that CI passes